spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: yun
#    password: "Y_yun1234"
#    url: jdbc:mysql://175.27.194.97:3306/loser?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC
    username: root
    password: "root"
    url: jdbc:mysql://127.0.0.1:3306/loser?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC

  mvc:
    static-path-pattern: /**
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-column-underline: true
    id-type: 0
    capital-mode: true

# 分页插件
pagehelper:
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
  row-bounds-with-count: true
  helper-dialect: mysql
server:
  port: 8088
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true

alipay:
#  你的沙箱APPID
  app-id:  "9021000158622522"
#  你的沙箱商户私钥
  private-key: "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCN5qPVVYoLDLgavcDMTx+sC+uKcBKyZaHHAJ6BDdZ5KquBx3hmegjJGSKIfOlWiNmKQVnmQ1jLXS0U3aXY4UVQjVzBzHoPbPZ6ocAWLTYbuGygQLvgqKOeXjFSm4hbpunugHllm+DW19K0Ey9ELzrUwyMgE8xfVLOkfv66a5956voCs4nvtpbZCM182V3hj22W7Szd9gr0EcsFvShdBSerysOdh+/TY38pN/RHGx80comhcJRG4ahiRdKEc38BICy9bWlDIqThad/z+qNxr75ybC5cungraswL2stsCgquuu1zkTYV/+fJzjr4mLnZULoOsD8DnJOQkGdum0gkusxxAgMBAAECggEAdFsaHnWMwzDDyhGshRugYehIVPU/L4+Mz2xfjH03T5XAmqNgw87vY0679WVPxIhksSyTNfAlYGRf8gsp0iQuPTYdSECOGhYEKlx18PlTs/lPATzzke1WdSbRlOY6MsU0b0BjywC9pg3FFanhiSydNhdotwXlAIqo34rO/zf+xe24C1kbNShWIhL5IWkuTHEdOaaVD9J/xr4JBu6sIoLwJ9SB8iS/vaCA7n9vFKPvqqRE9N+rd7NFIc92sT51x6HGZpgbdIdGVw1buUvKOLvdZMJTD5S1vcUjhfFqiwLg0tDbOGM3PpOhyvoEa9u3wrlq/9/U9HyxSOZaIEQsnbP6AQKBgQD2GZK6gRXsnMk9IZmbuMfcciDz5tevQ3SCN1xnp1OJ5Yn+mBTBa2Yl3omjqPdSVFVPXC/grv4fQsf4Gzs3FHyA/ONwXJcH7QZRUVuovMcEOt6IyEmcDPt6cKXv29dVBRCXXsY7aHLPLDHNoJdXGPZEQMY9CORlU3ejXs2t14rykQKBgQCTm/zf4oqtxxLNdZ1xrCmJD41hWvgd1z1qKr54Us1twvQM3EwV6fVS7p1ZL/kRXvHpoPnfS1nDeVfJzRiimPJlkNd6fuujD2uBEw7HFYIhLF1UKuQlbRqvL2+j5Yn34qQ707LfHaNtSyCZxXAfDSigs18GkyvRPgvk4FmO1ylr4QKBgQCLMP2fROFsmWTskXN68vD/iwF+UcMN2t4rxDocWjRSmyQIfmXG3ALDSnGYwjlYNGCn6SEfOHp8nd3SQzyjs4+TuPS+mW/GyNW46oYoEtWRW+Z/gKC5hVI69zmzRyksahfvNWhzM2k0Ke/lOH5AgdrP0b8NyFi9wo65NSapu25YMQKBgEpebgJyxgIV6YBAwMlzvx2CC25Agf+u4Q9rZ7mBpmSls4YDPAZScLqO5BH6XJeG6YUXCK2a7ifRLAzNW5sYShAn8JiT966Y50YJzwk46e5CxubQEVBV7vrSgIHn9SJCOxK1b0qASUWYc11mHz5Vx+FnXfoXDh2HEEEJU7Xm68ShAoGATk/MEqVAqhAKKCa5bI9BBMJWPRJrZrRUDmofe8f0L6Bst739BzoCJDuP+rF0Pgy11NMTxnwoyMQPsd+wBgYXGfgoaH5G4UymkCURRGZFU95HZ62t5y2WgVxg4CGf25yE/2Cc3ioBUX6BFle84WGMgtEPfit/oefqMnmAEgGgrmc="
  #    你的沙箱支付宝公钥
  public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhtgaWvGWOLqCaHNjKKWvzv7r6LYuEuEWsvkYfBpVbUrIvoJAR/1mNXyVmxrAYZTJ/EW1LhBXKywGTm+H8dSg148P5vyNCMiqtlnTlb1FQL9Lb74Y+utZonAY7xXuM/Pkyy/9I/jP6yNAw+7FRIRSWhfjdoeeDdmh7+uB64vKirKsPpUZpOnWBJ50P6oll+XtLy5J0PCFgzUGv7s+iV3Rias0Gz2eESzL6RkWLTFfKabBvz6dUdOOZhlXUB0Ir9RYGEOgbz3U+OZeoGzYmzBsFvjVXRuKnLbrfFW+aFiK9ZhMpWTAmVMoWqsFGMbB2znR4sAXIc7FtoYoHjZN3+05VwIDAQAB"

